repos:
  # Fix end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - '--fix=lf'

  # Remove unused imports/variables
  - repo: https://github.com/myint/autoflake
    rev: v2.3.0
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-unused-variable"
          - "--ignore-init-module-imports"

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
        args:
          - --profile
          - black

  # Black formatting
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    - id: black
      language_version: python3
      args:
        - --line-length=120

  # Flake8 linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args:
        - --ignore=E203,E402,E501,W291,W503
        - --max-line-length=120
